server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /dsp/admin/ {
        proxy_pass http://admin-service:8082/;
    }

    location /dsp/api/ {
        proxy_pass http://data-service:8080/;
    }

    location /dsp/offline/ {
        proxy_pass http://offline-service:8081/;
    }
}
